# Created by DQCodegen
spring:
  cloud:
    stream:
      bindings:
        smsVerificationCreatedPublish:
          destination: ${CHANNEL_PREFIX:}${SMS-VERIFICATION-CREATED:sms-verification-created}
        smsVerificationDeliveredSubscribe:
          destination: ${CHANNEL_PREFIX:}${SMS-VERIFICATION-DELIVERED:sms-verification-delivered}
          group: ${DEMO:demo}
