
spring:
  datasource:
    driverClassName: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: ${DB_TEST_QUERY:}
      maximumPoolSize: ${HIKARI_MAXIMUM_POOLSIZE:10}
      minimumIdle: ${HIKARI_MINIMUM_IDLE:10}
      idleTimeout: ${HIKARI_IDLE_TIMEOUT:600000}
      connectionTimeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      maxLifetime: ${HIKARI_MAX_LIFETIME:1800000}      
