spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://DEMO
          predicates:
            - Path=/v1/**


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-uereka: true